"""Скрипт для генерации SQL схемы базы данных.

Использует Tortoise ORM для генерации DDL всех таблиц.
"""

import asyncio
import sys

from pathlib import Path


# Добавляем src в PYTHONPATH
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from tortoise import Tortoise


TORTOISE_ORM = {
    "connections": {"default": "sqlite://:memory:"},
    "apps": {
        "models": {
            "models": [
                "infra.adapters.db.models",
                "aerich.models",
            ],
            "default_connection": "default",
        },
    },
}


async def generate_schema():
    """Генерирует SQL DDL схему для всех моделей."""
    print("=" * 80)
    print("ГЕНЕРАЦИЯ СХЕМЫ БАЗЫ ДАННЫХ")
    print("=" * 80)
    print()

    # Инициализация Tortoise
    await Tortoise.init(config=TORTOISE_ORM)

    # Генерация SQL
    print("-- Generated by Tortoise ORM")
    print("-- Database schema for LOTTY A/B Platform")
    print()

    # Получаем SQL для создания таблиц
    sql = Tortoise.get_schema_sql(
        Tortoise.get_connection("default"), safe=False
    )
    print(sql)

    print()
    print("=" * 80)
    print("ИНДЕКСЫ И ОПТИМИЗАЦИИ")
    print("=" * 80)
    print()

    # Список критичных индексов
    critical_indexes = [
        (
            "experiments",
            "flag_key, status",
            "get_active_by_flag_key performance",
        ),
        ("decisions", "decision_id", "event attribution performance"),
        ("events", "decision_id, event_type_key", "report aggregation"),
        ("events", "subject_id, timestamp", "user funnels"),
    ]

    for table, columns, purpose in critical_indexes:
        print(f"-- Index on {table}({columns})")
        print(f"-- Purpose: {purpose}")
        print()

    await Tortoise.close_connections()


async def show_table_stats():
    """Показывает статистику по таблицам."""
    await Tortoise.init(config=TORTOISE_ORM)

    print()
    print("=" * 80)
    print("СТАТИСТИКА ТАБЛИЦ")
    print("=" * 80)
    print()

    from infra.adapters.db.models import (
        ApprovalModel,
        DecisionModel,
        EventModel,
        EventTypeModel,
        ExperimentModel,
        FeatureFlagModel,
        GuardrailConfigModel,
        MetricModel,
        UserModel,
        VariantModel,
    )

    models = [
        ("users", UserModel),
        ("feature_flags", FeatureFlagModel),
        ("experiments", ExperimentModel),
        ("variants", VariantModel),
        ("approvals", ApprovalModel),
        ("guardrail_configs", GuardrailConfigModel),
        ("decisions", DecisionModel),
        ("events", EventModel),
        ("event_types", EventTypeModel),
        ("metrics", MetricModel),
    ]

    print(f"{'Таблица':<25} {'Модель':<30}")
    print("-" * 55)
    for table_name, model_class in models:
        print(f"{table_name:<25} {model_class.__name__:<30}")

    print()
    print(f"Всего таблиц: {len(models)}")

    await Tortoise.close_connections()


if __name__ == "__main__":
    print("Генерация SQL схемы...")
    print()
    asyncio.run(generate_schema())
    asyncio.run(show_table_stats())
